#! /usr/bin/env python

import yoda

aos = yoda.read("test1.yoda", False, patterns=r".*_(eta|mass)_(2|4)")
print aos
assert len(aos) == 4

import re
aos = yoda.read("test1.yoda", False, patterns=[r".*_y_(1|3)", re.compile(r".*_dphi_(2|4)")])
print aos
assert len(aos) == 3

aos = yoda.read("test1.yoda", False, patterns=[r".*_y_(1|3)", re.compile(r".*_dphi_(2|4)")], unpatterns=r".*_y_1")
print aos
assert len(aos) == 2
