#! /usr/bin/env bash

yodamerge test1.yoda test2.yoda -o merged12.yoda
yodadiff merged12.yoda merged12-ref.yoda

yodamerge test1.yoda:2 test2.yoda:3.142 -o merged12pi.yoda
yodadiff merged12pi.yoda merged12pi-ref.yoda
