#! /usr/bin/env python

"""\
Usage: %prog file1.yoda [file2.yoda ...]

Produce plottable histogram data files comparing sets of histograms from YODA
analysis data files.
"""

import optparse
op = optparse.OptionParser(usage=__doc__)
opts, args = op.parse_args()

## Load histos and attach annotations
import yoda

def parse_arg(arg):
    "Function to parse a command line arg and return the filename + dict of command-line annotations"
    argparts = arg.split(":")
    fname = argparts[0]
    anns = {}
    for ann in argparts[1:]:
        if "=" in ann:
            aname, aval = ann.split("=")
            anns[aname] = aval
        else:
            anns["Title"] = ann
    return fname, anns

## Parse command line args into filename and associated annotations
fnames, fname_anns = [], []
for a in args:
    fname, anns = parse_arg(a)
    fnames.append(fname)
    fname_anns.append(anns)

# TODO: convert all to Scatters?

## Load ref data objects and apply annotations
refaos = yoda.read(fnames[0])
for p, ao in refaos.iteritems():
    for k, v in fname_anns[0].iteritems():
        ao.setAnnotation(k, v)

## Load non-ref data objects into a dict of lists, and apply annotations
# TODO: should include default color/style cycling
cmpaolists = {}
for i, f in enumerate(fnames[1:], start=1):
    cmpaos = yoda.read(f)
    for p, ao in cmpaos.iteritems():
        for k, v in fname_anns[i].iteritems():
            ao.setAnnotation(k, v)
        cmpaolists.setdefault(ao.path, []).append(ao)

print refaos
print
print cmpaolists
